name: tlearning
channels:
  - conda-forge
dependencies:
  - keras-preprocessing >=1.1.2,<1.2
  - numpy >=1.19.2,<1.20
  - tensorboard==2.6.0
  - tensorflow-hub==0.12.0
  - tensorflow==2.5.0
  - pillow
  - matplotlib
